kind: Deployment
apiVersion: apps/v1
metadata:
  name: infordata-poc-qa
  namespace: qa
  labels:
    app: infordata-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infordata-qa
  template:
    metadata:
      labels:
        app: infordata-qa
    spec:
      containers:
        - name: infordata
          image: de.icr.io/infordata_poc_ir/infordata-gs-poc:v1
          env:
          - name: ORACLE_USERNAME
            valueFrom:
              secretKeyRef:
                name: oracle
                key: ORA_USER
          - name: ORACLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oracle
                key: ORA_PASSWORD
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600