kind: Deployment
apiVersion: apps/v1
metadata:
  name: infordata-poc
  labels:
    app: infordata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infordata
  template:
    metadata:
      labels:
        app: infordata
    spec:
      containers:
        - name: infordata-poc
          image: de.icr.io/infordata_poc_ir/infordata-gs-poc:v1
          env:
          - name: ORACLE_USERNAME
            valueFrom:
              secretKeyRef:
                name: oracle
                key: ORA_USER
          - name: ORACLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oracle
                key: ORA_PASSWORD
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: oracle
                key: ORA_INSTANCE
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600