kind: Deployment
apiVersion: apps/v1
metadata:
  name: infordata-poc-stagig
  namespace: dev
  labels:
    app: infordata-poc-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infordata-poc-staging
  template:
    metadata:
      labels:
        app: infordata-poc-staging
    spec:
      containers:
        - name: infordata-staging
          image: de.icr.io/infordata_poc_ir/infordata-dev:v2.2
          env:
          - name: ORACLE_USERNAME
            valueFrom:
              secretKeyRef:
                name: oracle
                key: ORA_USER
          - name: ORACLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oracle
                key: ORA_PASSWORD
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
