kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: infordata-poc
  labels:
    app: infordata
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: >-
    infordata-poc-stagig-dev.infordata-cluster-2bef1f4b4097001da9502000c44fc2b2-0000.eu-de.containers.appdomain.cloud
  to:
    kind: Service
    name: infordata-poc
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
