kind: Service
apiVersion: v1
metadata:
  name: infordata-poc
  labels:
    app: infordata
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: infordata
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}